### ISSUE TITLE
Internet Explorer support?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [visjs/vis-network#166]
I am wondering if it's possible to get this supported in IE?

**Comment by Thomaash** [comment]
This?

**Comment by PrzemyslawKlys** [comment]
Well, this JS library. As in network diagrams. Sorry for not being specific enough. It seems to work on Chrome, Edge, Firefox, Edge Chromium, just IE 11 not working. Was wondering if it's possible or not really?

**Comment by Thomaash** [comment]
IE11 is supported (see https://browserl.ist/?q=%3E+0.1%25+or+not+dead for all supported browsers and versions) and should work. Any example of this not working? Any errors?

**Comment by PrzemyslawKlys** [comment]
This: https://github.com/EvotecIT/PSWriteHTML/blob/master/Examples/Example31-NestedTabs/Example30-NestedTabs.html

On the right side on first tab there's a diagram. The important thing is that PSWriteHTML generates "Local" files and most users use them from disk directly without any web server.

![image](https://user-images.githubusercontent.com/15063294/67149840-80c3eb00-f2b0-11e9-80f1-c8dcc067671b.png)

**Comment by Thomaash** [comment]
Does it work if you use https://github.com/Thomaash/vis-network/blob/peer-build/standalone/umd/vis-network.js instead of the version you're using now?

**Comment by PrzemyslawKlys** [comment]
That one works... is it different than the one I use? Or just because I hosted it locally worked?

**Comment by Thomaash** [comment]
It uses core js 3 instead of the dated core js 2.

**Comment by PrzemyslawKlys** [comment]
Right, I saw some esm.js errors. Is it hosted on any CDN?

**Comment by Thomaash** [comment]
Officially? No. But you can get it through https://raw.githack.com/.

**Comment by PrzemyslawKlys** [comment]
Any ETA for official?

**Comment by Thomaash** [comment]
No ETA is set. @mojoaxel had some issues with it and didn't review it after they were addressed.

Maybe you could have a look at it this weekend @mojoaxel?

**Comment by mojoaxel** [comment]
> Maybe you could have a look at it this weekend @mojoaxel?

I just approved the changes.

**Comment by PrzemyslawKlys** [comment]
Since IE support still doesn't seem to work, is it possible to reopen this?

**Comment by Thomaash** [comment]
Yeah, sure, this should be reopened.

**Comment by szabi** [comment]
ESM module system/loading is not supported by IE (even Version 11), but it is by Edge. Maybe that's the root of the issue?

**Comment by PrzemyslawKlys** [comment]
The test version that @Thomaash provided worked in IE. That means it should be possible to get it up and running.

**Comment by Thomaash** [comment]
I think I finally figured out why there were so many weird and seemingly random issues. To put it shortly we were polyfilling polyfills (up to five layers of polyfills in the worst case) which is a really stupid thing to do. It sometimes fails, sometimes works and sometimes it obscures issues in underling packages.

There are three PRs opened right now addressing this and after they're merged and the updated packages are updated (this is a bit complicated process because we use dependency hell design pattern) it should work.

**Comment by PrzemyslawKlys** [comment]
Will it potentially resolve my issues from https://github.com/visjs/vis-network/issues/139 ?

**Comment by Thomaash** [comment]
I copy pasted the code into a file and replaced the unpkg.com version with the one from my test build. Once the icon font is loaded/cached everything works as expected. Though was not able to reproduce your issue back then either.

Maybe it was polyfilling issue. Polyfills often depend on slight nuances to decide whether a polyfill should be applied or the native implementation used. It's possible that some polyfill failed due to this only in your environment but not in mine and caused the problem. Or maybe not. I really don't know.

**Comment by PrzemyslawKlys** [comment]
We will see :-) Thank you!

**Comment by Thomaash** [comment]
Actually you can test it yourself right now: [vis-network.zip](https://github.com/visjs/vis-network/files/3884053/vis-network.zip).

**Comment by PrzemyslawKlys** [comment]
No, no change.

**Comment by PrzemyslawKlys** [comment]
This seems to work with 6.4.6. Thank you!
